name: Caller Workflow Rong
on:
  workflow_dispatch:
    inputs:
      username:
        required: true
        description: name of user
        default: test
      open:
        required: false
        description: open or not
        default: 'false'
      minutes:
        required: false
        description: minute
        default: '1'
jobs:
  translate:
    name: translate minutes to seconds
    runs-on: ubuntu-latest
    steps:
    - name: translate minutes to seconds
      env:
        MINUTES: ${{ github.event.inputs.minutes }}
      run: |
        export SECONDS=$(($MINUTES*60))
        echo $SECONDS
  run:
    name: run reusable workflow
    uses: ./.github/workflows/reusable-workflow-1.yml
    with:
      username: ${{ github.event.inputs.username }}
      open: ${{ github.event.inputs.open }}
      age: '123'
      seconds: $SECONDS
    needs: [translate]
