name: Caller Workflow Rong
on:
  workflow_dispatch:
    inputs:
      minutes:
        required: true
        description: minutes
        default: '1'
jobs:
  translate:
    name: translate minutes to seconds
    runs-on: ubuntu-latest
    steps:
    - name: translate minutes to seconds
      env:
        MINUTES: ${{ github.event.inputs.minutes }}
      run: |
        export SECONDS=$(($MINUTES*60))
        echo $SECONDS
  run:
    name: run reusable workflow
    uses: ./.github/workflows/parallel.yml
    with:
      minutes: ${{github.event.inputs.minutes}}
  print:
    name: print env
    runs-on: ubuntu-latest
    steps:
      - run: echo $SECONDS
    needs: [translate]
