name: dynamic-matrix
on:
  workflow_dispatch:
jobs:
  generate_colors:
    runs-on: ubuntu-latest

    outputs:
      colors: ${{ steps.colors.outputs.colors }}

    steps:
      - uses: actions/checkout@v4

      - name: Define Colors
        id: colors
        run: |
          script/generate_colors.sh

  use_colors:
    runs-on: ubuntu-latest
    needs: define-matrix
    strategy:
      matrix:
        color: [${{ fromJSON(needs.generate_colors.outputs.colors) }}]

    steps:
      - name: Report Colors
        run: |
          printf "\n\n Matrix parameters: ${{ matrix.color }}"
