name: dynamic-matrix
on:
  workflow_dispatch:
jobs:
  generate-colors:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.colors.outputs.matrix }}

    steps:
      - uses: actions/checkout@v4

      - name: Define Colors
        id: colors
        run: script/generate_color.sh

      - name: Debug GITHUB_OUTPUT
        run: cat $GITHUB_OUTPUT

  use-colors:
    runs-on: ubuntu-latest
    needs: generate-colors
    strategy:
      matrix:
        color: ${{ fromJSON(needs.generate-colors.outputs.matrix.colors) }}

    steps:
      - name: Report Colors
        run: |
          printf "\n\n Matrix parameters: ${{ matrix.color }}"
