name: dynamic-matrix
on:
  workflow_dispatch:
jobs:
  define-matrix:
    runs-on: ubuntu-latest

    outputs:
      colors: ${{ steps.colors.outputs.colors }}

    steps:
      - uses: actions/checkout@v4
      - name: Define Colors
        id: colors
        run: |
          ls
          pwd
#          script/generate_color.sh >> "$GITHUB_OUTPUT"
#
#  produce-atrifacts:
#    runs-on: ubuntu-latest
#    needs: define-matrix
#    strategy:
#      matrix:
#        color: ${{ fromJSON(needs.define-matrix.outputs.colors) }}
#
#    steps:
#      - name: Report Colors
#        run: |
#          printf "\n\n Matrix parameters: ${{ matrix.color }}"
#
#
