name: try input
on:
  workflow_call:
    inputs:
      startNumber:
        description: 'startNumber'
        required: true
        type: string
        default: '0'
      range:
        description: 'startNumber'
        required: true
        type: string
        default: '0'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name : print
        run: |
          printf "\n\n Input parameters, number from ${{ inputs.startPhoneNumber }} to $(( ${{inputs.startPhoneNumber }} + ${{ inputs.phoneNumberRange }} ))"
