name: Reusable workflow 1
on:
  workflow_call:
    inputs:
      username:
        required: true
        type: number
        default: 1
      open:
        required: true
        type: boolean
        default: true
      age:
        required: true
        type: string
        default: '1'
jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - run: echo "welcome ${{ inputs.username }}"
