name: Reusable workflow 1
on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
        default: 'string'
      open:
        required: true
        type: string
        default: 'true'
      age:
        required: true
        type: string
        default: '1'
      seconds:
        required: true
        type: string
      numPoolAccounts:
        required: false
        type: string
        default: '1'
      numShadowAccounts:
        required: false
        type: string
        default: '123'

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - run: echo "welcome ${{ inputs.username }}"
      - run: echo "second is ${{ inputs.seconds }}"
      - run: echo "${{ inputs.age }}"
      - run: echo "${{ inputs.numShadowAccounts }}"
      - run: echo "${{ inputs.age }}"
      - run: echo "${{ inputs.numPoolAccounts }}"



